default: &default
  adapter: postgresql
  encoding: utf8

local_default: &local_default
  <<: *default
  min_messages: warning
  pool: 2
  timeout: 5000
  host: localhost

development:
  <<: *local_default
  database: protecting_our_river_development

test:
  <<: *local_default
  database: protecting_our_river_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
